### ISSUE TITLE
Request to discuss best practices for approaching the NIH data management plan requirements

### ISSUE THREAD

**Issue by Jen-OMalley** [AlexsLemonade/reproducible-research#117]
We received a suggestion from a 2023 October participant who is interested in discussing the new NIH data management plan requirements. If it is possible to make a decision on this and add to our materials in a maximum of 2 days, we may incorporate this request into our content. 

`I was wondering at the workshop whether there might be a chance to discuss best practices for and/or how you are approaching the new NIH data management plan requirements. Seems like that would be super useful for young investigators in particular.`

Tagging @jaclyn-taroni.

**Comment by jaclyn-taroni** [comment]
Thanks, Jen! 

First, I want to note that my 10000-foot understanding of the [2023 NIH Data Management and Sharing Policy](https://sharing.nih.gov/data-management-and-sharing-policy/about-data-management-and-sharing-policies/data-management-and-sharing-policy-overview) is that the requirements significantly overlap with [ALSF's policy](https://www.alexslemonade.org/sites/default/files/images/alsf1/downloads/alsf_resource_sharing_policy-rev_april_2023.pdf). I agree that training on this topic is helpful for early career researchers.

Right now, we briefly cover data management in the context of the project organization material. I was recently made aware of [the Center for Open Science Training Workshops](https://www.cos.io/services/training). They have a hands-on data management kickstarter module; [the material is available and openly licensed](https://osf.io/4uv2a/).

We are unlikely to be able to cover writing an NIH DMP specifically, but we should evaluate if there's additional information we can adapt from the COS material about managing files and generalist repositories and add to the project organization section.

**Comment by sjspielman** [comment]
Dumping some thoughts here for discussion (also has bearing on #121), CC the J Team (i'm not sorry for writing that) @jaclyn-taroni @jashapiro @Jen-OMalley

### Useful links

- CC0 slides from Pitt: https://pitt-my.sharepoint.com/:p:/g/personal/hes85_pitt_edu/EbovafXlYPhLpV6Nu-HOxeEBlRu7BUIKQ8Ey2pPbcqcTMQ?rtime=3fMaU2PA20g
- NIH's policy landing page
- NIH-recommended repositories
  - generalist: https://sharing.nih.gov/data-management-and-sharing-policy/sharing-scientific-data/generalist-repositories
  - specialist/sciencey: https://sharing.nih.gov/data-management-and-sharing-policy/sharing-scientific-data/repositories-for-sharing-scientific-data 

### Thought dump


Our goal for these slides should focus on practical tips and suggestions for how to share data in a way that meets NIH's, and similarly ALSF's (as a bonus, since similar policies), guidelines. Given the rest of the material in RRP, we shouldn't focus on "why care about data sharing." In addition, we are not the NIH and cannot speak on behalf of NIH, so these are simply our opinions on being compliant with their policy.

Given that a lot of RRP content is highly relevant to data sharing in general, I see two spots that make the most sense to slot this in (see the June 2022 schedule):

- Option A: After "Project Organization." 
	- Close conceptual link between project organization and successful data management/sharing
	- Motivates a lot of the rest of the workshop 
- Option B: At the end of the workshop
	- They've seen the tools/concepts we've introduced, so now we can bring it all together when discussing how these relate to data management practices
	- But, is fatigue a problem at this point? Or will this wake them back up?!


#### Loose Talk Outline

I think we should aim for <=20 minutes here to allow for Q/A & discussion. I am anticipating a good amount of questions here.

- Open with NIH policy and highlight sections that overlap with ALSF.
	- This should be pretty quick! We are not NIH.
- Discuss what is meant by "data"
	- It's not just your reads, it's _all your data_, including the raw & processed data as presented in the paper. 
		- Seriously, you need to always retain an "untouched" version of each dataset. Summarizing its stats etc. does not give you permission to delete it.
	- It's not just your data, it's _documentation about your data_. If nobody knows how to use it, did you really share it?
	- But data & docs need to be separate files, please. Get those formulas/plots out of your spreadsheets to achieve more FAIRness.
- We can show an example of a paper with SI excel spreadsheets that have all the data for each figure (OpenPBTA?)
	- But look, the data is _not only_ in SI!
- Discuss repositories
	- Reiterate, supplementary information is not a repository. It cannot be the only destination for your data.
	- GitHub is not suitable for a lot of data types/sizes. NIH has good lists (except the Dryad bit!). 
	- Generalist repos are just as important - reiterate that all data is data, not just reads/imaging/etc.
- Strategies for success
	- Before starting your project, decide how your team will organize and document the data. Maybe have a policy, and try not to sleep on the docs.
		- harken (yes, it appears I've written harken?) back to project organization slides - you'll probably need a complementary system to that. 
		- this includes a _naming system_
	- Back up the data in some way. 
	- Feeling spicy? Version the data (this is a bonus topic, since it's a bit advanced!)

**Comment by Jen-OMalley** [comment]
Just dropping the link to the [DMPTool](https://dmptool.org/) (Data Management Planning Tool). May be another resource to consider sharing? People can use this to find the [NIH default template](https://dmptool.org/public_templates?page=1&search=nih) and a [variety of data management plans](https://dmptool.org/public_plans?search=nih&sort_by=created_at) submitted by other NIH-funded researchers to reference.

Ooh perhaps, we may want to add the relevant resources we share during RRP to the [data and resource sharing section](https://www.ccdatalab.org/research-resources#data-sharing) of our research resources page on ccdatalab.org!

**Comment by sjspielman** [comment]
> Please tell me we can pronounce it "dump tool"

They did it to themselves and now must reap what they have sown. Approved.

**Comment by sjspielman** [comment]
I've drafted these slides to a point where it's ready for some initial feedback before a second round from me: https://docs.google.com/presentation/d/10NEkqHkAw9KBAbkNV-vtPwLFc9ZHksHEcCFty32efiE/edit#slide=id.g290a9e71aec_0_30 

CC @jaclyn-taroni @jashapiro @allyhawkins please feel free to directly comment! In particular, I'm interested to know what content needs to be expanded or removed. Organizational recommendations also appreciated (noting that those specific recommendations may shift as content gets added/removed). Changes to styling can also happen later, but feel free to point out spots that really need to be prettier!

**Comment by sjspielman** [comment]
These slides are largely done, and we'll track getting them into the schedule with #122.
