### ISSUE TITLE
October 2023: Update slides and add pdfs

### ISSUE THREAD

**Issue by sjspielman** [AlexsLemonade/reproducible-research#120]
This issue will track adding updating slides & adding PDFs to the repo. 

Previously, we used slide links in the schedule as well as a big pdf of _all_ slides.

For this time around, let's add individual slide deck PDFs to `workshop_materials/slides` and link those from the schedule, as we do for "regular" trainings. We should each take "our own" slides - 

- [x] [Welcome](https://docs.google.com/presentation/d/1-mPY76_AbS8rLqxoSAOc2Ews5GyPSo8PVuG2El_S6BE/edit?usp=sharing) @jashapiro
- [x] [Why does reproducibility matter?](https://docs.google.com/presentation/d/1qfulAR4jD0KS7NfrLHpwT6SWl-7APBmqNnAwGpXX5oo/edit?usp=sharing) @sjspielman 
- [x] [Project organization](https://docs.google.com/presentation/d/1ncqxXlC0-PGEK-yE7S-nDYnMPhrOUPbI95EJy283wCs/edit?usp=sharing) @jashapiro 
- [x] [Introduction to UNIX and the command line](https://docs.google.com/presentation/d/1WPXkItJZEUXMY20cLrdMXHiBC2PyunR14RUSDg4nfIc/edit?usp=sharing) @sjspielman 
- [x] [Introduction to Git; Forking and cloning a repository](https://docs.google.com/presentation/d/1eiGZA4PYBKJx5HDCo3UDOAB7q415gg96TehxilCHwlA/edit?usp=sharing) @jashapiro 
- [x] [Shell scripting](https://docs.google.com/presentation/d/1SDUyYVNgvDDRodVqmDQPVQ5wnjQesWfBTg0EAcdbcSo/edit?usp=sharing) @sjspielman 
- [x] [The git stage/commit/push workflow and `.gitignore` files](https://docs.google.com/presentation/d/1_YckNhAkp_82PKR6PGS5SdaKDgoueYVTXaPi5pQV9ik/edit?usp=sharing) @sjspielman 
- [x] [Organizing code in scripts and notebooks](https://docs.google.com/presentation/d/1AJr6uQhwLnZfis1wNc_e2XY4XSMEuVscIfAsVgnM5Bk/edit?usp=sharing) @jashapiro 
- [x]  [Managing packages and environments](https://docs.google.com/presentation/d/1GCbu2F6LeEPOu5DzDsTgwu1__9YDVydvPo911fBG1i0/edit?usp=sharing) @jashapiro 
- [x] [Working with branches in Git](https://docs.google.com/presentation/d/1s7BSHgTSDuXIzI1ROS-JSneB6NXfQVWOec6lhc8eIWA/edit?usp=sharing) @sjspielman

**Comment by sjspielman** [comment]
@jashapiro I've gone through my slides and updated for this workshop. Not too many changes, mostly some typo fixes and a few small (really small!) spots where I reorganized or cleaned up text. For the UNIX slides I also updated some of my terminal screen shots, but I didn't do this for the gitkraken slides since there were quite a few at a very specific point in git history and didn't think it was worth the effort. Similarly, gitkraken screen shots could really also be redone to look a little nicer, but again, didn't think it was worth the effort, in part b/c we'll zip through them as background during in favor of spending time actually demonstrating doing the things live.

Please feel free to add direct comments to slides or any overall comments here, and I'll convert to PDFs after you've doe an initial look over things - if you could comment in this issue when you're done with comments that would be great, thanks! **OR** if you prefer I file PRs with the PDFs sooner, lmk!

- [Why does reproducibility matter?](https://docs.google.com/presentation/d/1qfulAR4jD0KS7NfrLHpwT6SWl-7APBmqNnAwGpXX5oo/edit?usp=sharing)
- [Introduction to UNIX and the command line](https://docs.google.com/presentation/d/1WPXkItJZEUXMY20cLrdMXHiBC2PyunR14RUSDg4nfIc/edit?usp=sharing) 
- [Shell scripting](https://docs.google.com/presentation/d/1SDUyYVNgvDDRodVqmDQPVQ5wnjQesWfBTg0EAcdbcSo/edit?usp=sharing)
- [The git stage/commit/push workflow and `.gitignore` files](https://docs.google.com/presentation/d/1_YckNhAkp_82PKR6PGS5SdaKDgoueYVTXaPi5pQV9ik/edit?usp=sharing)
- [Working with branches in Git](https://docs.google.com/presentation/d/1s7BSHgTSDuXIzI1ROS-JSneB6NXfQVWOec6lhc8eIWA/edit?usp=sharing)

**Comment by jashapiro** [comment]
I added a few comments, but overall everything looks good.

**Comment by sjspielman** [comment]
> I added a few comments, but overall everything looks good.

Thanks!!

**Comment by jashapiro** [comment]
> For this time around, let's add individual slide deck PDFs to `workshop_materials/slides` and link those from the schedule, as we do for "regular" trainings. We should each take "our own" slides -

Do we maybe want to just link to the google slides?

**Comment by sjspielman** [comment]
> Do we maybe want to just link to the google slides?

Yeah, that's definitely fine with me. But, I wonder (and I really wonder, not sure!) if we should "version" these in a `2023` folder in the drive?

**Comment by jashapiro** [comment]
I have updated the slides for my parts, please leave me any comments!

The biggest changes are in the intro, as you might expect, which got a whole new file.
I updated the schedule, but didn't make changes to the people slides, aside from adding a QR code (linked if you click on it!) for UXR recruiting. I thought about more updates to the people slides, but I probably want to see what others think. 

I'm not sure if there are other logistics we want to be sure to include; the room change is highlighted, but I didn't put when we would meet for walking over to dinner on there, for example. I thought @Jen-OMalley might want to weigh in there.

The other significant changes are in Intro to Git, where I updated screenshots to show new GitHub interface.

I also added an Anatole picture in the Project Organization slides, to help people understand my references.

I didn't update the `renv` screenshots, despite a bunch of version number changes, because none of the commands changed and the output isn't significantly different.

Links below:

* [Welcome](https://docs.google.com/presentation/d/1-mPY76_AbS8rLqxoSAOc2Ews5GyPSo8PVuG2El_S6BE/edit?usp=sharing)
 * [Project organization](https://docs.google.com/presentation/d/1ncqxXlC0-PGEK-yE7S-nDYnMPhrOUPbI95EJy283wCs/edit?usp=sharing) 
* [Introduction to Git](https://docs.google.com/presentation/d/1eiGZA4PYBKJx5HDCo3UDOAB7q415gg96TehxilCHwlA/edit?usp=sharing) 
* [Organizing code in scripts and notebooks](https://docs.google.com/presentation/d/1AJr6uQhwLnZfis1wNc_e2XY4XSMEuVscIfAsVgnM5Bk/edit?usp=sharing) 
*  [Managing packages and environments](https://docs.google.com/presentation/d/1GCbu2F6LeEPOu5DzDsTgwu1__9YDVydvPo911fBG1i0/edit?usp=sharing)

**Comment by Jen-OMalley** [comment]
@jashapiro I swapped my photo in the people slides for a newer one. 🙂 

We are going to tell people to meet in the lobby by 5:30pm to walk or Lyft (depending on the weather or people's preferences) to dinner. We should at least mention that out loud. If you want to include it in the slides too, that's the plan!

**Comment by sjspielman** [comment]
@jashapiro Changes all look fine to me, left a couple comments mostly in the new slides as you'd expect. I made a few direct changes like changing lowercase git -> uppercase Git where I saw it, and changed some font size (I indicated this with a comment).

**Comment by sjspielman** [comment]
Slide links all added to schedule!
